adjusted the instructions in step2.md to include switching to Tab1 be…
derberg/asyncapi-killercoda-interactive-tutorials pull request #1
Opened 2022-11-07 19:36 UTC by activus-d

## Issue Summary
This Pull Request improved on the instructions in [step2.md](https://github.com/activus-d/asyncapi-killercoda-interactive-tutorials/blob/main/streetlight-tut/step2.md) by informing the user to switch to a different terminal (Tab 1) and enter the output directory (with cd output) from there.

2022-11-07 20:45 UTC, alequetzalli commented
@derberg **Interactive** Streetlights tutorial update PR

2022-11-07 20:47 UTC, alequetzalli commented on streetlight-tut/step2.md
> +1. And voilà! In the editor you can see a new folder is created with generated Node.js application. Goto your `Tab1` terminal and enter the `output` folder from the there: `cd output`{{exec}}
```suggestion
1. And voilà! In the editor you can see a new folder is created with generated Node.js application. Go to your `Tab1` terminal and enter the `output` folder from there: `cd output`{{exec}}
```

2022-11-07 20:47 UTC, alequetzalli requested changes
left my review ✌🏽

2022-11-07 22:10 UTC, activus-d commented
Thanks for the review @alequetzalli

2022-11-08 09:56 UTC, derberg commented
@activus-d thanks so much for taking the time to let us know about the issue, figuring out where to fix it, and in the end, fixing it 🙏🏼 🍺

2022-11-08 09:56 UTC, merged